# Generated by Django 4.0.3 on 2022-03-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='creds',
            field=models.IntegerField(default=0),
        ),
    ]
