# Generated by Django 4.0.3 on 2022-03-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(choices=[('ACCESSORIES', 'accessory'), ('ELECTRONICS', 'electronics'), ('HEALTH', 'health'), ('HOME DECORATIONS', 'home'), ('WEARABLES', 'wearings')], default='ACCESSORIES', max_length=25)),
                ('affiliate_link', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='products')),
            ],
        ),
    ]
