# Generated by Django 4.0.3 on 2022-03-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLinks',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(choices=[('ACCESSORIES', 'accessory'), ('ELECTRONICS', 'electronics'), ('HEALTH', 'health'), ('HOME DECORATIONS', 'home'), ('WEARABLES', 'wearings')], default='ACCESSORIES', max_length=25)),
                ('affiliate_link', models.CharField(max_length=1000)),
                ('product_seller', models.CharField(choices=[('AMAZON', 'AMAZON'), ('FLIPKART', 'FLIPKART'), ('NYKAA', 'NYKAA'), ('SNAPDEAL', 'SNAPDEAL'), ('MESH', 'MESH'), ('OTHER', 'OTHER')], default='FLIPKART', max_length=25)),
                ('link_adder', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='products')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
