# Generated by Django 4.0.3 on 2022-03-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_productlinks_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlinks',
            old_name='link_adder',
            new_name='influencer',
        ),
        migrations.RemoveField(
            model_name='productlinks',
            name='product_category',
        ),
    ]
