# Generated by Django 4.0.3 on 2022-03-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0004_productlinks_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlinks',
            name='image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
