# Generated by Django 4.0.3 on 2022-03-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0005_alter_productlinks_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlinks',
            name='website',
            field=models.CharField(choices=[('AMAZON', 'AMAZON'), ('FLIPKART', 'FLIPKART'), ('NYKAA', 'NYKAA'), ('SNAPDEAL', 'SNAPDEAL'), ('MESH', 'MESH'), ('OTHER', 'OTHER')], default='AMAZON', max_length=25),
        ),
        migrations.AlterField(
            model_name='productlinks',
            name='product_seller',
            field=models.CharField(max_length=100),
        ),
    ]
