# Generated by Django 4.0.3 on 2022-03-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0006_productlinks_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlinks',
            name='image',
            field=models.CharField(default='https://unsplash.com/photos/sxiSod0tyYQ', max_length=1000),
        ),
    ]
